apiVersion: ENC[AES256_GCM,data:jUk=,iv:ICrVMaw7o5pBtXS9JQWdq+Avxp0Pi3ILgtY+8A0mHQM=,tag:GXUsOgKl3aTcHGMw0azcyQ==,type:str]
kind: ENC[AES256_GCM,data:Julfdqxk,iv:L83nvpvvOWuD6TWqjYyOp/eNSKrN2ExbuLFBMrE/xs4=,tag:nWSFmTRrRv3HnJuvxb5CcQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Xt1FzfpWaDNzKzTc,iv:KwvGL4CUIiMZkmrOx2pFWxZReQw+sR3OgBg7KTFEGco=,tag:hV58HF0PBnadifIsnZgoLg==,type:str]
    namespace: ENC[AES256_GCM,data:acDkVAeT,iv:jSqRocCO0zrP4enI3kBwkeuEBmfg4fM2YAg2RUfbGIM=,tag:mn9umdHsA9gZP/tcTjnjWQ==,type:str]
type: ENC[AES256_GCM,data:UaCLnRMs,iv:in01wkxJI9MMBwi64Oj1vzNbpbMRAOL8G6yj2Px3vKc=,tag:FxImutZQvmQHGChn/XgMoQ==,type:str]
data:
    password: ENC[AES256_GCM,data:gz7HkA==,iv:1UncipJ+EB5c8/mgRXhuxItM0LKp/s5AlzyUiYCFxws=,tag:GF5afaCiyJ3cQnfcw6bZ5Q==,type:str]
sops:
    age:
        - recipient: age1dcjryzpfkrpr82lcjh7twese80g0wcqe5c5mhqmkkry7xj5ar46stjq8xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRmEzRWczZ0VISUhxQnZz
            YkRrUU05eG9LMjl6UDFvWUkwN0N6eHh3OTBvCnZneURBVWJYRnNCWnpKalo0Tndh
            MHdlZEJYZEhyZTRVRTBGSEQ4RHNGNDAKLS0tIGFyZm5jdHBUZkJpWWZubG43T291
            WUp2R2xHalhFa3Rma0hJd1YvblJ4MGMKzMCbUREyWbznKSfM35ZxV+wdNXMrQUPd
            ePbBIyIDUDEVVK307HYSwSKfvZmnLuROMHQWjscgkHoUCjLpu2U7SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T14:49:28Z"
    mac: ENC[AES256_GCM,data:QMDDvzjpaE0jGB93b1Aqo5yuZzQ7Fz+rdCtm79n6ZI6m/G51+Rz8gwpOBVvFvaCVrYBg9v148dQ5p5RMW29wLik4CS7ap/r9JjDZe+DXRvkRNtXuifERYCVNcI0c8b8fAsn5h0Pwjl6/4t/reXuepbM9jpN9Xxu443mikkrQHTM=,iv:bMnrg+o0ZdvvOQCf5SiofnFRI3D+5y1/txZEbqqYGtw=,tag:uKbNNytEKoAgAz0D1kDz7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
