apiVersion: ENC[AES256_GCM,data:EaA=,iv:LlfoKp+DkJ9zn+yusAXOo8tYmpj4mW8Bh77alyMHIKM=,tag:ITjVTIfSmiXu0FbGa/VyAw==,type:str]
kind: ENC[AES256_GCM,data:szgz2OWX,iv:xJuvUso50/mn2ebfYhs6M0so4+oTCs4QxKzXRuOezB0=,tag:DwRuqbTwdXbr/WVdJcXhiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8QLadRhwS50I,iv:ACShD3V5tckIZaG7ZYJLN/nZVUgKwFLfmKrNNQXFl3o=,tag:LH285GMfj7n61Y+5SiKgAw==,type:str]
    namespace: ENC[AES256_GCM,data:q7OdFPem,iv:Gm//7O7/Z+nWEwKchgYPh5hOFw9IJ3oYaXUz253O49E=,tag:NoeKB3tcKr3HNuFU9zNk7g==,type:str]
type: ENC[AES256_GCM,data:dzyC/vxs,iv:bCL08sQCrTmC8szSJSq4TDjDniImTikJERqIpOAE0Xw=,tag:Sn0k3X3k+trDY4Q6LLzYJA==,type:str]
data:
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:gSY+tw==,iv:Wvuq2CtSNsHEZWAi+zlQjJM5myxwi7LgqiWvPyZw7aA=,tag:CAgrFv5ViIKxFU5J1v5Y2g==,type:str]
sops:
    age:
        - recipient: age1dcjryzpfkrpr82lcjh7twese80g0wcqe5c5mhqmkkry7xj5ar46stjq8xk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmRnBMdndUNlZEWjNZcG0y
            L1BlR3JoUjhiUXMvak1QMzRSd0x5NXVPU2ljCkllZnF6dG5BVFBMdWRKZUFodXNu
            SVJYOVBFWDlHMVNHT1lJL3FQWmlyTHMKLS0tIGlEZlhsbzdsQkRBZTJZMUxWQjFh
            RG5kYVdpQnBBZldUNmg5VDdYWS9vNFkKY1l9KLOYj7vcDFAlbBZKifxS3k5e8ODi
            mloxFJCkqx77lttj0+tEBOJgSSzUXWPuLFg5HtvlC5ideGY+YtjBvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T15:34:18Z"
    mac: ENC[AES256_GCM,data:oj09dN/nAbfYpkfxrN58lB1MWGkaBCDzy1Hb4Ml7iDwEjjbCt26kIdH3UoPFn8nqFfYsdH+ZWTQvQZIOysM041u5a/qiiVJghs/kGZJF/Jpxgza8ajwPMU3CBEzDMqF1QFcAzTeBFdn0PrlUgo4GhVTvxjrBhEsVzFaMit+2GWM=,iv:crj0jZQ21ahlgq6P4dT3oIXt7qHou99y6G1ZoBbdKkg=,tag:v3ozFdnqEc+RBMOPFZc+7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
