apiVersion: v1
kind: Service
metadata:
  name: coflow-backend
  labels:
    app: coflow-backend
spec:
  selector:
    app: coflow-backend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP