apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusters-apps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/__overlays/lab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decrypt:
    provider: sops
    secretRef:
      name: sops-keys
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: external-settings
    - kind: Secret
      name: secret-settings