apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: coflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: mysql
          image: ghcr.io/jorgevizu4/database:main-fea7bf0
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:                                                                                                                 
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql.coflow.svc.cluster.local:3306/coflow?useSSL=false&allowPublicKeyRetrieval=true"
          - name: SPRING_DATASOURCE_USERNAME                                                                                 
            value: root                                                                                              
          - name: SPRING_DATASOURCE_PASSWORD                                                                               
            value: root