apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coflow
resources:
- namespace.yaml
- network-policy.yaml
# - ./coflow-backend/
# - ./coflow-frontend/
# - ./coflow-database/
- ./coflow/