apiVersion: apps/v1
kind: Deployment
metadata:
  name: coflow
  labels:
    app: coflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coflow
  template:
    metadata:
      labels:
        app: coflow
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: frontend
        image: ghcr.io/jorgevizu4/frontend-web:main-cbd9fa1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      - name: backend
        image: ghcr.io/jorgevizu4/backend:main-cbd9fa1
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql.coflow.svc.cluster.local:3306/coflow?useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: JWT_SECRET_KEY
          value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
