apiVersion: networking.k8s.io/v1                                                                                     
kind: Ingress                                                                                                        
metadata:                                                                                                            
  name: coflow-ingress                                                                                               
  labels:                                                                                                            
    app: coflow                                                                                                      
spec:
  ingressClassName: nginx
  rules:
  - host: coflow-frontend.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: coflow-frontend
            port:
              number: 8081
      - path: /
        pathType: Prefix
        backend:
          service:
            name: coflow-frontend
            port:
              number: 80