apiVersion: v1
kind: Service
metadata:
  name: coflow-frontend
  labels:
    app: coflow
spec:
  selector:
    app: coflow
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: backend
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP