apiVersion: apps/v1
kind: Deployment
metadata:
  name: coflow-backend
  namespace: coflow
  labels:
    app: coflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coflow-backend
  template:
    metadata:
      labels:
        app: coflow-backend
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: backend
        image: ghcr.io/jorgevizu4/backend:main-cbd9fa1
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql.default.svc.cluster.local:3306/coflow
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update
        - name: SPRING_SQL_INIT_MODE
          value: never
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_DATA_REST_BASE_PATH
          value: ""
        - name: SPRING_WEB_CORS_ALLOW_CREDENTIALS
          value: "false"
        - name: SPRING_APPLICATION_NAME
          value: backend
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: JWT_SECRET_KEY
        - name: JWT_EXPIRATION_MS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: JWT_EXPIRATION_MS